<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Sushi\Sushi;

class Currency extends Model
{
    use Sushi;

    public function getRows()
    {
        return [
            ['iso' => 'usd', 'symbol' => '$', 'currency' => 'United States Dollar'],
            ['iso' => 'aed', 'symbol' => 'د.إ', 'currency' => 'UAE Dirham'],
            ['iso' => 'amd', 'symbol' => '', 'currency' => 'Armenian Dram'],
            ['iso' => 'ang', 'symbol' => 'ƒ', 'currency' => 'Netherlands Antillean Guilder'],
            ['iso' => 'aud', 'symbol' => '$', 'currency' => 'Australian Dollar'],
            ['iso' => 'awg', 'symbol' => 'ƒ', 'currency' => 'Aruban Florin'],
            ['iso' => 'azn', 'symbol' => '₼', 'currency' => 'Azerbaijanian Manat'],
            ['iso' => 'bam', 'symbol' => 'KM', 'currency' => 'Convertible Mark'],
            ['iso' => 'bbd', 'symbol' => '$', 'currency' => 'Barbados Dollar'],
            ['iso' => 'bdt', 'symbol' => '৳', 'currency' => 'Taka'],
            ['iso' => 'bgn', 'symbol' => 'лв', 'currency' => 'Bulgarian Lev'],
            ['iso' => 'bif', 'symbol' => '', 'currency' => 'Burundi Franc'],
            ['iso' => 'bmd', 'symbol' => '$', 'currency' => 'Bermudian Dollar'],
            ['iso' => 'bnd', 'symbol' => '$', 'currency' => 'Brunei Dollar'],
            ['iso' => 'bsd', 'symbol' => '$', 'currency' => 'Bahamian Dollar'],
            ['iso' => 'bwp', 'symbol' => 'P', 'currency' => 'Pula'],
            ['iso' => 'bzd', 'symbol' => 'BZ$', 'currency' => 'Belize Dollar'],
            ['iso' => 'cad', 'symbol' => '$', 'currency' => 'Canadian Dollar'],
            ['iso' => 'cdf', 'symbol' => '', 'currency' => 'Congolese Franc'],
            ['iso' => 'chf', 'symbol' => 'CHF', 'currency' => 'Swiss Franc'],
            ['iso' => 'cny', 'symbol' => '¥', 'currency' => 'Yuan Renminbi'],
            ['iso' => 'dkk', 'symbol' => 'kr', 'currency' => 'Danish Krone'],
            ['iso' => 'dop', 'symbol' => 'RD$', 'currency' => 'Dominican Peso'],
            ['iso' => 'dzd', 'symbol' => '', 'currency' => 'Algerian Dinar'],
            ['iso' => 'egp', 'symbol' => '£', 'currency' => 'Egyptian Pound'],
            ['iso' => 'etb', 'symbol' => '', 'currency' => 'Ethiopian Birr'],
            ['iso' => 'eur', 'symbol' => '€', 'currency' => 'Euro'],
            ['iso' => 'fjd', 'symbol' => '$', 'currency' => 'Fiji Dollar'],
            ['iso' => 'gbp', 'symbol' => '£', 'currency' => 'Pound Sterling'],
            ['iso' => 'gel', 'symbol' => '', 'currency' => 'Lari'],
            ['iso' => 'gip', 'symbol' => '£', 'currency' => 'Gibraltar Pound'],
            ['iso' => 'gmd', 'symbol' => '', 'currency' => 'Dalasi'],
            ['iso' => 'gyd', 'symbol' => '$', 'currency' => 'Guyana Dollar'],
            ['iso' => 'hrk', 'symbol' => 'kn', 'currency' => 'Kuna'],
            ['iso' => 'htg', 'symbol' => '', 'currency' => 'Gourde'],
            ['iso' => 'ils', 'symbol' => '₪', 'currency' => 'New Israeli Sheqel'],
            ['iso' => 'isk', 'symbol' => 'kr', 'currency' => 'Iceland Krona'],
            ['iso' => 'jmd', 'symbol' => 'J$', 'currency' => 'Jamaican Dollar'],
            ['iso' => 'jpy', 'symbol' => '¥', 'currency' => 'Yen'],
            ['iso' => 'kes', 'symbol' => '', 'currency' => 'Kenyan Shilling'],
            ['iso' => 'kgs', 'symbol' => 'лв', 'currency' => 'Som'],
            ['iso' => 'khr', 'symbol' => '៛', 'currency' => 'Riel'],
            ['iso' => 'kmf', 'symbol' => '', 'currency' => 'Comoro Franc'],
            ['iso' => 'krw', 'symbol' => '₩', 'currency' => 'Won'],
            ['iso' => 'kzt', 'symbol' => 'лв', 'currency' => 'Tenge'],
            ['iso' => 'lbp', 'symbol' => '£', 'currency' => 'Lebanese Pound'],
            ['iso' => 'lkr', 'symbol' => '₨', 'currency' => 'Sri Lanka Rupee'],
            ['iso' => 'lrd', 'symbol' => '$', 'currency' => 'Liberian Dollar'],
            ['iso' => 'lsl', 'symbol' => '', 'currency' => 'Loti'],
            ['iso' => 'mad', 'symbol' => '', 'currency' => 'Moroccan Dirham'],
            ['iso' => 'mdl', 'symbol' => '', 'currency' => 'Moldovan Leu'],
            ['iso' => 'mga', 'symbol' => '', 'currency' => 'Malagasy Ariary'],
            ['iso' => 'mkd', 'symbol' => 'ден', 'currency' => 'Denar'],
            ['iso' => 'mmk', 'symbol' => '', 'currency' => 'Kyat'],
            ['iso' => 'mnt', 'symbol' => '₮', 'currency' => 'Tugrik'],
            ['iso' => 'mop', 'symbol' => '', 'currency' => 'Pataca'],
            ['iso' => 'mvr', 'symbol' => '', 'currency' => 'Rufiyaa'],
            ['iso' => 'mwk', 'symbol' => '', 'currency' => 'Kwacha'],
            ['iso' => 'mxn', 'symbol' => '$', 'currency' => 'Mexican Peso'],
            ['iso' => 'myr', 'symbol' => 'RM', 'currency' => 'Malaysian Ringgit'],
            ['iso' => 'mzn', 'symbol' => 'MT', 'currency' => 'Mozambique Metical'],
            ['iso' => 'nad', 'symbol' => '$', 'currency' => 'Namibia Dollar'],
            ['iso' => 'ngn', 'symbol' => '₦', 'currency' => 'Naira'],
            ['iso' => 'nok', 'symbol' => 'kr', 'currency' => 'Norwegian Krone'],
            ['iso' => 'npr', 'symbol' => '₨', 'currency' => 'Nepalese Rupee'],
            ['iso' => 'nzd', 'symbol' => '$', 'currency' => 'New Zealand Dollar'],
            ['iso' => 'pgk', 'symbol' => '', 'currency' => 'Kina'],
            ['iso' => 'php', 'symbol' => '₱', 'currency' => 'Philippine Peso'],
            ['iso' => 'pkr', 'symbol' => '₨', 'currency' => 'Pakistan Rupee'],
            ['iso' => 'pln', 'symbol' => 'zł', 'currency' => 'Zloty'],
            ['iso' => 'qar', 'symbol' => '﷼', 'currency' => 'Qatari Rial'],
            ['iso' => 'ron', 'symbol' => 'lei', 'currency' => 'Romanian Leu'],
            ['iso' => 'rsd', 'symbol' => 'Дин.', 'currency' => 'Serbian Dinar'],
            ['iso' => 'rub', 'symbol' => '₽', 'currency' => 'Russian Ruble'],
            ['iso' => 'rwf', 'symbol' => '', 'currency' => 'Rwanda Franc'],
            ['iso' => 'sar', 'symbol' => '﷼', 'currency' => 'Saudi Riyal'],
            ['iso' => 'sbd', 'symbol' => '$', 'currency' => 'Solomon Islands Dollar'],
            ['iso' => 'scr', 'symbol' => '₨', 'currency' => 'Seychelles Rupee'],
            ['iso' => 'sek', 'symbol' => 'kr', 'currency' => 'Swedish Krona'],
            ['iso' => 'sgd', 'symbol' => '$', 'currency' => 'Singapore Dollar'],
            ['iso' => 'sll', 'symbol' => '', 'currency' => 'Leone'],
            ['iso' => 'sos', 'symbol' => 'S', 'currency' => 'Somali Shilling'],
            ['iso' => 'szl', 'symbol' => '', 'currency' => 'Lilangeni'],
            ['iso' => 'thb', 'symbol' => '฿', 'currency' => 'Baht'],
            ['iso' => 'tjs', 'symbol' => '', 'currency' => 'Somoni'],
            ['iso' => 'top', 'symbol' => '', 'currency' => 'Pa\'anga'],
            ['iso' => 'try', 'symbol' => '₺', 'currency' => 'Turkish Lira'],
            ['iso' => 'ttd', 'symbol' => 'TT$', 'currency' => 'Trinidad and Tobago Dollar'],
            ['iso' => 'twd', 'symbol' => 'NT$', 'currency' => 'New Taiwan Dollar'],
            ['iso' => 'tzs', 'symbol' => '', 'currency' => 'Tanzanian Shilling'],
            ['iso' => 'uah', 'symbol' => '₴', 'currency' => 'Hryvnia'],
            ['iso' => 'ugx', 'symbol' => '', 'currency' => 'Uganda Shilling'],
            ['iso' => 'uzs', 'symbol' => 'лв', 'currency' => 'Uzbekistan Sum'],
            ['iso' => 'vnd', 'symbol' => '₫', 'currency' => 'Dong'],
            ['iso' => 'vuv', 'symbol' => '', 'currency' => 'Vatu'],
            ['iso' => 'wst', 'symbol' => '', 'currency' => 'Tala'],
            ['iso' => 'xaf', 'symbol' => '', 'currency' => 'CFA Franc BEAC'],
            ['iso' => 'xcd', 'symbol' => '$', 'currency' => 'East Caribbean Dollar'],
            ['iso' => 'yer', 'symbol' => '﷼', 'currency' => 'Yemeni Rial'],
            ['iso' => 'zar', 'symbol' => 'R', 'currency' => 'Rand'],
            ['iso' => 'zmw', 'symbol' => '', 'currency' => 'Zambian Kwacha'],
        ];
    }
}
